apiVersion: v1
kind: ConfigMap
data:
  policy.csv: |
    p, role:readonly, applications, get, *, allow
    g, crunchops, role:readonly
  resource.customizations: |
    v1/ConfigMap:
      ignoreDifferences: |
        jsonPointers:
          - /metadata/resourceVersion
          - /metadata/creationTimestamp
          - /metadata/annotations/meta.helm.sh/release-name
          - /metadata/annotations/meta.helm.sh/release-namespace
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2024-11-01T09:49:03Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-3.35.4
  name: argocd-rbac-cm
